package com.example.ffixvalert.model

import com.squareup.moshi.Json

data class AllServerStatus(
    @Json(name = "Adamantoise")
    val adamantoise: List<Any>,
    @Json(name = "Aegis")
    val aegis: List<Any>,
    @Json(name = "Alexander")
    val alexander: List<Any>,
    @Json(name = "Anima")
    val anima: List<Any>,
    @Json(name = "Asura")
    val asura: List<Any>,
    @Json(name = "Atomos")
    val atomos: List<Any>,
    @Json(name = "Bahamut")
    val bahamut: List<Any>,
    @Json(name = "Balmung")
    val balmung: List<Any>,
    @Json(name = "Behemoth")
    val behemoth: List<Any>,
    @Json(name = "Belias")
    val belias: List<Any>,
    @Json(name = "Brynhildr")
    val brynhildr: List<Any>,
    @Json(name = "Cactuar")
    val cactuar: List<Any>,
    @Json(name = "Carbuncle")
    val carbuncle: List<Any>,
    @Json(name = "Cerberus")
    val cerberus: List<Any>,
    @Json(name = "Chocobo")
    val chocobo: List<Any>,
    @Json(name = "Coeurl")
    val coeurl: List<Any>,
    @Json(name = "Diabolos")
    val diabolos: List<Any>,
    @Json(name = "Durandal")
    val durandal: List<Any>,
    @Json(name = "Excalibur")
    val excalibur: List<Any>,
    @Json(name = "Exodus")
    val exodus: List<Any>,
    @Json(name = "Faerie")
    val faerie: List<Any>,
    @Json(name = "Famfrit")
    val famfrit: List<Any>,
    @Json(name = "Fenrir")
    val fenrir: List<Any>,
    @Json(name = "Garuda")
    val garuda: List<Any>,
    @Json(name = "Gilgamesh")
    val gilgamesh: List<Any>,
    @Json(name = "Goblin")
    val goblin: List<Any>,
    @Json(name = "Gungnir")
    val gungnir: List<Any>,
    @Json(name = "Hades")
    val hades: List<Any>,
    @Json(name = "Hyperion")
    val hyperion: List<Any>,
    @Json(name = "Ifrit")
    val ifrit: List<Any>,
    @Json(name = "Ixion")
    val ixion: List<Any>,
    @Json(name = "Jenova")
    val jenova: List<Any>,
    @Json(name = "Kujata")
    val kujata: List<Any>,
    @Json(name = "Lamia")
    val lamia: List<Any>,
    @Json(name = "Leviathan")
    val leviathan: List<Any>,
    @Json(name = "Lich")
    val lich: List<Any>,
    @Json(name = "Louisoix")
    val louisoix: List<Any>,
    @Json(name = "Malboro")
    val malboro: List<Any>,
    @Json(name = "Mandragora")
    val mandragora: List<Any>,
    @Json(name = "Masamune")
    val masamune: List<Any>,
    @Json(name = "Mateus")
    val mateus: List<Any>,
    @Json(name = "Midgardsormr")
    val midgardsormr: List<Any>,
    @Json(name = "Moogle")
    val moogle: List<Any>,
    @Json(name = "Odin")
    val odin: List<Any>,
    @Json(name = "Omega")
    val omega: List<Any>,
    @Json(name = "Pandaemonium")
    val pandaemonium: List<Any>,
    @Json(name = "Phoenix")
    val phoenix: List<Any>,
    @Json(name = "Ragnarok")
    val ragnarok: List<Any>,
    @Json(name = "Ramuh")
    val ramuh: List<Any>,
    @Json(name = "Ridill")
    val ridill: List<Any>,
    @Json(name = "Sargatanas")
    val sargatanas: List<Any>,
    @Json(name = "Shinryu")
    val shinryu: List<Any>,
    @Json(name = "Shiva")
    val shiva: List<Any>,
    @Json(name = "Siren")
    val siren: List<Any>,
    @Json(name = "Spriggan")
    val spriggan: List<Any>,
    @Json(name = "Tiamat")
    val tiamat: List<Any>,
    @Json(name = "Titan")
    val titan: List<Any>,
    @Json(name = "Tonberry")
    val tonberry: List<Any>,
    @Json(name = "Twintania")
    val twintania: List<Any>,
    @Json(name = "Typhon")
    val typhon: List<Any>,
    @Json(name = "Ultima")
    val ultima: List<Any>,
    @Json(name = "Ultros")
    val ultros: List<Any>,
    @Json(name = "Unicorn")
    val unicorn: List<Any>,
    @Json(name = "Valefor")
    val valefor: List<Any>,
    @Json(name = "Yojimbo")
    val yojimbo: List<Any>,
    @Json(name = "Zalera")
    val zalera: List<Any>,
    @Json(name = "Zeromus")
    val zeromus: List<Any>,
    @Json(name = "Zodiark")
    val zodiark: List<Any>
)